<?php

return [
    'NET_WORKING_LIMIT' => 5,
    'LIMIT_NETWORKING_PER_NAME' => 6,
    'LIMIT_EXHIBITORS' => 6,
    'LIMIT_VISITORS' => 6,
    'MATCHING_EXCLUDE_STATUSES' => [],
    'STATUS' => [
        'DEAL_DONE' => 4,
    ],
    'CHAT_PROFILE_CONTENTS_DEFAULT_FIELD_KEYS' => env('CHAT_PROFILE_CONTENTS_DEFAULT_FIELD_KEYS', ''),
    'CHAT_PROFILE_INFORMATION' => env('CHAT_PROFILE_INFORMATION', ''),
    'LIVE_CHAT_EXHIBITOR_TEXT' => env('LIVE_CHAT_EXHIBITOR_TEXT', '出展者'),
];
